server {
    # On écoute uniquement sur le port 443 (le port standard du HTTPS)
    listen 443 ssl;
    listen [::]:443 ssl;

    # Le nom de domaine de ton site
    server_name yaoberso.42.fr;

    # Les chemins vers ton certificat de sécurité (qu'on va créer dans le Dockerfile juste après)
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    # Les protocoles autorisés
    ssl_protocols TLSv1.2 TLSv1.3;

    # Le dossier racine où seront stockés les fichiers de ton site WordPress
    root /var/www/wordpress;
    
    # Le fichier qui sera lu en premier par défaut
    index index.php index.html index.htm;

    # Si on tape une URL, on essaie de trouver le fichier, sinon on renvoie une erreur 404
    location / {
        try_files $uri $uri/ =404;
    }

    # C'EST LA PARTIE LA PLUS IMPORTANTE : Le lien avec WordPress
    # Si Nginx voit qu'on lui demande un fichier qui se termine par ".php", 
    # il l'envoie au conteneur WordPress (sur le port 9000) pour qu'il le lise.
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass wordpress:9000;
    }
}